### Importing Packages and Loading Data

In [1]:
import pandas as pd
import os
from email.parser import Parser

In [2]:
POI = ['lay-k', 'skilling-j']
folders = ['sent', 'deleted_items', 'discussion_threads', 'notes_inbox']
mdir = r"C:\Users\AlexaJohnston\Springboard\Enron_Investigation_Capstone\Enron_Investigation"
email_data = []

In [3]:
for person in POI: #for each person in the list POI
    person_path = os.path.join(mdir, person) #create a single path from the main repo to the persons in POI
    for folder in os.listdir(person_path): #create a list of the subfolder for each person
        if any(key in folder.lower() for key in folders): #if any word in a person's folder matches a word in folders
            folder_path = os.path.join(person_path, folder) #look at every file inside the folders that match the words i folders
            for file in os.listdir(folder_path): #for every file in folder path create a list of files
                file_path = os.path.join(folder_path, file) #join the path for the folder with the file
                if os.path.isfile(file_path): #check to make sure each item in file path is a file
                    with open(file_path, 'r', errors='ignore') as f: #Open and read every file, regardless of errors
                        msg = Parser().parsestr(f.read()) #decodes the text into an email format
                        email_data.append({ #creates a dictionary of the fields
                            'date': msg['Date'], 
                            'from': msg['From'],
                            'to': msg['To'], 
                            'subject': msg['Subject'], 
                            'body': msg.get_payload(), 
                            'custodian': person, 
                            'folder_source': folder
                        })
df = pd.DataFrame(email_data) #makes the dictionary into a dataframe
print(f"Success! Captured {len(df)} high-value emails.")

Success! Captured 5359 high-value emails.

### Data Overview

In [4]:
df.head()

,date,from,to,subject,body,custodian,folder_source
0,"Wed, 30 Jan 2002 11:06:10 -0800 (PST)",grnthumb@ipa.netf,klay@enron.com,Demand Ken Lay Donate Proceeds from Enron Stoc...,"Linda Brunner\n12335 S. 2225 Rd.\nStockton, MO...",lay-k,deleted_items
1,"Wed, 30 Jan 2002 11:39:03 -0800 (PST)",avanleunen@msn.com,klay@enron.com,Demand Ken Lay Donate Proceeds from Enron Stoc...,"alice van leunen\n13631 NE Kinney Rd\nNewberg,...",lay-k,deleted_items
2,"Wed, 30 Jan 2002 11:42:03 -0800 (PST)",comet@starshaper.com,klay@enron.com,Demand Ken Lay Donate Proceeds from Enron Stoc...,John-Paul Goorjian\ncomet@starshaper.com\n\nTo...,lay-k,deleted_items
3,"Wed, 30 Jan 2002 09:57:08 -0800 (PST)",manastassatos@randomhouse.com,klay@enron.com,Demand Ken Lay Donate Proceeds from Enron Stoc...,Marietta Anastassatos\n435 Highland Ave\nPalis...,lay-k,deleted_items
4,"Wed, 30 Jan 2002 09:57:10 -0800 (PST)",kmitchel@coba.usf.edu,klay@enron.com,Demand Ken Lay Donate Proceeds from Enron Stoc...,Kimberly Mitchell\n1906 E. Linda Street\nPlant...,lay-k,deleted_items

In [5]:
df.tail()

,date,from,to,subject,body,custodian,folder_source
5354,"Wed, 12 Apr 2000 04:40:00 -0700 (PDT)",sherri.sera@enron.com,maktay@superonline.com,Hi...,"Metin,\n\nGreat to hear from you. Believe it ...",skilling-j,_sent_mail
5355,"Mon, 10 Apr 2000 10:52:00 -0700 (PDT)",sherri.sera@enron.com,annb@redstonegrp.com,RE: Message from Gary Stein,Ugh! :-) Just kidding...I figured it would be ...,skilling-j,_sent_mail
5356,"Mon, 10 Apr 2000 10:38:00 -0700 (PDT)",sherri.sera@enron.com,annb@redstonegrp.com,RE: Message from Gary Stein,I shall be there. Just let me know what time ...,skilling-j,_sent_mail
5357,"Mon, 10 Apr 2000 10:05:00 -0700 (PDT)",sherri.sera@enron.com,annb@redstonegrp.com,Re: Message from Gary Stein,"Ann, I haven't heard from you with regard to w...",skilling-j,_sent_mail
5358,"Fri, 7 Apr 2000 10:11:00 -0700 (PDT)",sherri.sera@enron.com,chuck.paul@a-closer-look.com,Re: Fw:,"Dear Mr. Paul,\n\nI'm writing on behalf of Jef...",skilling-j,_sent_mail

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5359 entries, 0 to 5358
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           5359 non-null   object
 1   from           5359 non-null   object
 2   to             5104 non-null   object
 3   subject        5359 non-null   object
 4   body           5359 non-null   object
 5   custodian      5359 non-null   object
 6   folder_source  5359 non-null   object
dtypes: object(7)
memory usage: 293.2+ KB

In [7]:
df['custodian'].value_counts()

custodian
lay-k         3375
skilling-j    1984
Name: count, dtype: int64

In [8]:
df[df['custodian'] == 'skilling-j']['from'].value_counts().head(10)

from
sherri.sera@enron.com            466
joannie.williamson@enron.com      99
jeff.skilling@enron.com           87
40enron@enron.com                 70
markskilling@hotmail.com          51
fredinvt@juno.com                 41
sherri.reinartz@enron.com         36
katherine.brown@enron.com         31
lisa.connolly@enron.com           26
enron.announcements@enron.com     25
Name: count, dtype: int64

In [9]:
df[df['custodian'] == 'lay-k']['from'].value_counts().head(10)

from
rosalee.fleming@enron.com        595
leonardo.pacheco@enron.com        52
brown_mary_jo@lilly.com           46
savont@email.msn.com              44
tori.wells@enron.com              41
katherine.brown@enron.com         30
elizabeth.davis@compaq.com        29
rob.bradley@enron.com             20
enron.announcements@enron.com     20
lizard_ar@yahoo.com               18
Name: count, dtype: int64

### Converting date column to datetime

In [10]:
df['date'].head()

0    Wed, 30 Jan 2002 11:06:10 -0800 (PST)
1    Wed, 30 Jan 2002 11:39:03 -0800 (PST)
2    Wed, 30 Jan 2002 11:42:03 -0800 (PST)
3    Wed, 30 Jan 2002 09:57:08 -0800 (PST)
4    Wed, 30 Jan 2002 09:57:10 -0800 (PST)
Name: date, dtype: object

In [11]:
df['date_clean'] = pd.to_datetime(df['date'], utc=True)

C:\Users\AlexaJohnston\AppData\Local\Temp\ipykernel_18012\1452036759.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date_clean'] = pd.to_datetime(df['date'], utc=True)

In [12]:
df = df[(df['date_clean'].dt.year >= 1998) & (df['date_clean'].dt.year <= 2001)]

In [13]:
df.head()

,date,from,to,subject,body,custodian,folder_source,date_clean
156,"Tue, 13 Nov 2001 11:14:52 -0800 (PST)",ohi_supporters@operationhope.org,klay@enron.com,The Latest Edition of Operation HOPE Inc.'s El...,\n \nHere It Is !!! \n[IMAGE]\nor copy and pa...,lay-k,deleted_items,2001-11-13 19:14:52+00:00
158,"Mon, 26 Nov 2001 17:37:47 -0800 (PST)",djtheroux@independent.org,lighthouse@independent.org,"THE LIGHTHOUSE: November 26, 2001","THE LIGHTHOUSE\n""Enlightening Ideas for Public...",lay-k,deleted_items,2001-11-27 01:37:47+00:00
1126,"Mon, 2 Aug 1999 08:33:00 -0700 (PDT)",ggalata@enron.co.uk,kenneth.lay@enron.com,Franco Bernabe's tel number,"Ken,\n\nI finally found Franco Bernabe's work ...",lay-k,discussion_threads,1999-08-02 15:33:00+00:00
1127,"Thu, 19 Aug 1999 02:18:00 -0700 (PDT)",rosalee.fleming@enron.com,expense.report@enron.com,Approval of Jeff Skilling's Expense Report,Kenneth Lay has approved the attached expense ...,lay-k,discussion_threads,1999-08-19 09:18:00+00:00
1128,"Mon, 21 Aug 2000 02:36:00 -0700 (PDT)",corry.bentley@enron.com,kenneth.lay@enron.com,Sacrifice,"Here in my group, and all over Enron, I see pe...",lay-k,discussion_threads,2000-08-21 09:36:00+00:00

In [14]:
df.tail()

,date,from,to,subject,body,custodian,folder_source,date_clean
5354,"Wed, 12 Apr 2000 04:40:00 -0700 (PDT)",sherri.sera@enron.com,maktay@superonline.com,Hi...,"Metin,\n\nGreat to hear from you. Believe it ...",skilling-j,_sent_mail,2000-04-12 11:40:00+00:00
5355,"Mon, 10 Apr 2000 10:52:00 -0700 (PDT)",sherri.sera@enron.com,annb@redstonegrp.com,RE: Message from Gary Stein,Ugh! :-) Just kidding...I figured it would be ...,skilling-j,_sent_mail,2000-04-10 17:52:00+00:00
5356,"Mon, 10 Apr 2000 10:38:00 -0700 (PDT)",sherri.sera@enron.com,annb@redstonegrp.com,RE: Message from Gary Stein,I shall be there. Just let me know what time ...,skilling-j,_sent_mail,2000-04-10 17:38:00+00:00
5357,"Mon, 10 Apr 2000 10:05:00 -0700 (PDT)",sherri.sera@enron.com,annb@redstonegrp.com,Re: Message from Gary Stein,"Ann, I haven't heard from you with regard to w...",skilling-j,_sent_mail,2000-04-10 17:05:00+00:00
5358,"Fri, 7 Apr 2000 10:11:00 -0700 (PDT)",sherri.sera@enron.com,chuck.paul@a-closer-look.com,Re: Fw:,"Dear Mr. Paul,\n\nI'm writing on behalf of Jef...",skilling-j,_sent_mail,2000-04-07 17:11:00+00:00

### Handling duplicates

In [15]:
count = len(df) 
df = df.drop_duplicates(subset=['date', 'from', 'subject', 'body'])
count_2 = len(df) 
print(f"Removed {count - count_2} duplicate emails.")

Removed 1754 duplicate emails.

### Handling missing data

In [16]:
df['to'].isnull().sum()

np.int64(186)

In [17]:
missing_to = df[df['to'].isnull()]
print(missing_to['folder_source'].value_counts())

folder_source
deleted_items         108
discussion_threads     73
notes_inbox             5
Name: count, dtype: int64

In [18]:
import numpy as np 
df['to'] = df['to'].replace(r'^\s*$', np.nan, regex=True)
df['to'] = df['to'].fillna('Unknown Recipient')

### Normalizing body

In [19]:
pd.set_option('display.max_colwidth', None)
df['body'].sample(5)

3497                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \nOn Monday July 16, more than 125 new full-time Analysts (including Tax and Global Technology) will be starting their careers at Enron.  Attached is a schedule of Orientation Topics, as well as an invitation to welcome these Analysts at a Happy Hour Monday evening.  It would be great if you could stop by, even for just a few minutes, to welcome them to the company.  For your convenience, the Happy Hour is at Farrago, which is less than 6 blocks from the Enron Building.   \n\nMembers of the Program regularly tell us that senior level interaction is an area that we can improve on, so your participation in events like this very important.  An RSVP is not required, but if you plan to attend, please let us know so we can prepare a name tag for you.  Feel free to extend this invitation to other senior members of your team.\n\nAs always, we appreciate your continued support of The Program.\n\nRegards,\nBilly  \n\n\nDistribution:\nPolicy Committee\nA&A Committee (Western only)\nRecruiting Executive Leads\n\n  \n\n
4992                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      This is correct.  SRS
1570                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Enron's Year-End 2000 Performance Management Process opens on:\n\n   WEDNESDAY, OCTOBER 25th.\n\nDuring this process, you will be able to suggest reviewers who can provide \nfeedback on your performance.  In addition, you may be requested to provide \nfeedback on fellow employees.  To participate in the feedback process, access \nthe Performance Management System (PEP) at http://pep.corp.enron.com .   Your \nUserID and Password are provided below.\n\nThe system will be open for feedback from October 25th - November 17th, and \nHelp Desk representatives will be available to answer questions throughout \nthe process.  You may contact the Help Desk at:\n\n   Houston:  1-713-853-4777, Option 4\n   London:  44-207-783-4040, Option 4\n   E-mail:  perfmgmt@enron.com\n\nDuring the year-end PRC process, employee profiles will be made available at \nmeetings.   If you haven't already done so, we encourage you to update your \npersonal information and current responsibilities before the meeting process \nbegins on November 20th.  Please access eHRonline at \nhttp://ehronline.enron.com (London users please go to http://home.enron.co.uk \n, click on Quick Links, and choose HR Online).\n\nYour User ID & Password are:\n\nUser ID: 90012923\n\nPassword: WELCOME
1223    Dear Mr. Lay:\n\nOn behalf of The Economist Group, I have the pleasure of inviting you to jo=\nin=20\na select group of your peers at the second in our series of US E-Business=\n=20\nSummits, "Strategic business transformation for chief executives in the=20\ndigital economy". The E-Business Summit will take place at the JW Marriott =\nin=20\nAtlanta on October 2nd-3rd and subsequently at the Ritz-Carlton Lenox in=20\nChicago on October 18th-19th. To learn more about this event visit us at=20\nwww.economistconferences.com.  Click on the Americas portion of the map to=\n=20\nfind this event.\n\nYour name has been included on a short list of the nation=01,s most powerfu=\nl=20\ncorporate decision-makers invited to attend the Summit as our guest. If you=\n=20\nwish to accept this invitation, please RSVP directly to Melissa Thoms on=20\n212.554.0605 or register online at www.economistconferences.com.  Click on=\n=20\nthe Americas section of the map and choose E-business Atlanta or Chicago. =\n=20\nYou can simply add $0 in the registration fee.\n\nThe Economist Group founded the US e-business series in March 2000 with=20\nsummits in New York and California. Speakers and delegates at those events=\n=20\nincluded the chief executives of Cisco Systems, Nike, Palm Inc, DoubleClick=\n,=20\nNordstrom.com, Fair Isaac, International Creative Management, Schlumberger,=\n=20\nBlock Drug Company and DLJdirect.\n\nThe purpose of the e-business series is to address the concerns of CEOs at=\n=20\ncorporations founded on old-economy principles as they struggle to respond =\nto=20\nthe imperatives created by web-enabled technology. Corporate leaders are=20\ninvited to learn from their peers at blue-chip companies who are now settin=\ng=20\nthe pace of change as they rethink vital business functions from supply cha=\nin=20\nto customer service.\n\nBill Emmott, Editor of The Economist, will serve as chairman of the Atlanta=\n=20\nSummit, and John Peet, Business Affairs Editor of The Economist, will chair=\n=20\nthe Chicago Summit.\n\nOther programme highlights can be viewed at www.economistconferences.com. o=\nr=20\nyou can view the highlights below:\n\n* A feature presentation from the DuPont executive leading the effort to=20\nalign management and IT strategies\n* The e-business thought leader who turned Delta Air Lines around on the=20\ncompany=01,s online relationships\n* Unilever=01,s brand guru=01,s research and findings on Internet branding\n* Ford=01,s head of e-business on efficiency, productivity and supply chain\n* FleetBoston and Merrill Lynch on creating a new business model for=20\nfinancial services\n* The venture capitalists behind Walmart.com and McDonald=01,s E-Mac on the=\n=20\nrelationship between vc and bricks and mortar\n* Enron Net Works on how online marketplaces will transform the company int=\no=20\na new-economy player\n* Sears on multichannel management and the integration of legacy and online=\n=20\nbusinesses\n* Case studies from senior strategists at American Honda Motor, Anheuser=20\nBusch and UPS\n\nPlease review the enclosed programme for more details. I look forward to=20\ngreeting you in Atlanta or Chicago.\n\nBest regards,\nLisa Weiner\nGeneral Manager
1880                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Mr. Lay,\n\nThank you in advance for taking time to meet with me.\n\nI wanted to let you know in advance the topics I would like to discuss.\n\nNow that I have been at EBS for a little over a year, I want to update you on \nmy\nprogress and experiences within EBS.\n\nThe other topic I would like to discuss with you is my pursuit of an MBA.  \nMore\nspecifically I wanted to gather some of your insight as to pros and cons of \nthis\npursuit and how having an MBA with a technical background positions me within\nEnron.\n\nI would also like to talk to you about the outside business interest of mine\nthat I mentioned the night of the RISE School fundraiser.  This interest\nfulfills my entrepreneurial desires and for that matter, I have been involved\nwith this company for the last five years and am one of three principles.\n\n\nBest regards,\n\nChad Modad\nSoftware Engineer\nEnron Broadband Services\nTel: 713-669-4070\nCell: 713-516-2347\n
Name: body, dtype: object

In [20]:
import re
df['body'] = df['body'].str.replace(r'\r\n|\r', '\n', regex=True)
df['body'] = df['body'].str.replace(r'\n+', '\n', regex=True)
df['body_inspect'] = df['body'].str.replace('\n', '')
print(df['body_inspect'].sample(1).iloc[0])

Good morning, Valerie.  I don't believe we did get the e-mail yesterday!!  Please resend.Rosalee"Petersen, Valerie" <valerie.petersen@yale.edu> on 11/07/2000 07:02:40 AMTo: "'Kenneth.Lay@enron.com'" <Kenneth.Lay@enron.com>cc:  Subject: RE: Panel on ValuationGreat. Let me know if you didn't get yesterday's email regarding Nov 20. Ithad the call-in number.Valerie-----Original Message-----From: Kenneth.Lay@enron.com [mailto:Kenneth.Lay@enron.com]Sent: Monday, November 06, 2000 6:28 PMTo: Garten, JeffreySubject: Re: Panel on ValuationKen Lay can do November 20 at 5 p.m. EST or November 27 at 6 p.m. EST.November 21 is not good for him.Thanks.Rosalee"Garten, Jeffrey" <jeffrey.garten@yale.edu> on 11/02/2000 10:51:36 AMTo:   "'Len@shv.com'" <Len@shv.com>, "'jdoerr@kpcb.com'" <jdoerr@kpcb.com>,      "'robg@real.com'" <robg@real.com>, "'larry_kanarek@mckinsey.com'"      <larry_kanarek@mckinsey.com>, "'HHK@sprintmail.com'"      <HHK@sprintmail.com>, "'kenneth.lay@enron.com'"      <kenneth.lay@enron.com>, "'blev@stern.nyu.edu'" <blev@stern.nyu.edu>,      "'jbneff@wellmanage.com'" <jbneff@wellmanage.com>,      "'nperetsman@allenco.com'" <nperetsman@allenco.com>,      "'hadlow@blackstone.com'" <hadlow@blackstone.com>,      "'carlsonl@blackstone.com'" <carlsonl@blackstone.com>,      "'depowell@cisco.com'" <depowell@cisco.com>,      "'David.L.Shedlarz@pfizer.com'" <David.L.Shedlarz@pfizer.com>,      "'rick/sherlund@gs.com'" <rick@gs.com>, "'jstiglitz@brookings.edu'"      <jstiglitz@brookings.edu>, "'Hal@sims.berkeley.edu'"      <Hal@sims.berkeley.edu>cc:   "'tim_koller@mckinsey.com'" <tim_koller@mckinsey.com>,      "'avalles@kpcb.com'" <avalles@kpcb.com>, "'Lliming@real.com'"      <Lliming@real.com>, "'jeanne_giles@mckinsey.com'"      <jeanne_giles@mckinsey.com>, "'rosalee.fleming@enron.com'"      <rosalee.fleming@enron.com>, "'kboles@allenco.com'"      <kboles@allenco.com>, "'dryan@cisco.com'" <dryan@cisco.com>,      "'jfielding@gs.com'" <jfielding@gs.com>, "'tmerkle@brook.edu'"      <tmerkle@brook.edu>, "'lucy@sims.berkeley.edu'"      <lucy@sims.berkeley.edu>, "'carolyn_hubbard@mckinsey.com'"      <carolyn_hubbard@mckinsey.com>, "Petersen, Valerie"      <valerie.petersen@yale.edu>Subject:  Panel on ValuationI am sorry for the delay in getting back to you with a revision of thepaper.Attached please find a revised summary by Tim Koller.  We hope it reflectswell the discussion of our previous meeting. Before the next meeting, it isour intention to send along the longer discussion paper that would mirrorthis summary.  I suggest this next meeting take place as a conference callat one of the following times.  Please indicate with an "X" in the boxesnext to the proposed dates which dates are good for you.               Monday, November 20, 5 p.m. EST     [ X  ]               Tuesday, November 21, 5 pm EST      [   ]               Monday November 27, 6 pm EST        [ X  ]We would like to get everyone's views in advance of this conference call,either in writing or by phone.  Please indicate below what your preferencewould be.  If a call is preferred, Valerie Petersen will contact yourofficeto set it up.               Call [   ]               Writing   [   ]There will be one last meeting scheduled after the conference call meetingtakes place to go over the final draft.Look forward to hearing from you.Thanks very much,Jeff <<SEC Doc Draft 1029 short.doc>>(See attached file: SEC Doc Draft 1029 short.doc)

In [21]:
df['body_clean'] = df['body_inspect']
df['body_clean'] = df['body_clean'].str.replace(r'(?i)(^|\s)(From:)', r'\1| \2', regex=True)
df['body_clean'] = df['body_clean'].str.replace(r'(?i)(^|\s)(To:)', r'\1| \2', regex=True)
df['body_clean'] = df['body_clean'].str.replace(r'(?i)(^|\s)(Subject:)', r'\1| \2', regex=True)
df['body_clean'] = df['body_clean'].str.replace(r'(?i)(Subject:.*?)(?=\s|$)', r'\1 |', regex=True)
df['body_clean'] = df['body_clean'].str.strip()
print(df['body_clean'].sample(1).iloc[0])

As of midnight, Saturday, October 7th, the Executive Reports Viewer will no longer be accessible at its current location, due to IT modifications.  The system has been redesigned to allow access via Internet Explorer (you cannot use Netscape).  The new location is http://ersys.corp.enron.com. This change will ONLY affect the viewing of the reports; it will NOT impact the publishing of the reports.A shortcut icon can be created by dragging the Internet Explorer Logo (located in the address field next to the URL) to the desktop.If you have any questions, please do not hesitate to call Kristin Walsh at 3-9510 or myself at 3-9307.Thank you for your understanding,Christa Winfrey

In [22]:
df.sample(3)

                                       date                    from  \
1546  Mon, 16 Oct 2000 23:48:00 -0700 (PDT)        jhduncan@aol.com
4223   Mon, 2 Oct 2000 10:32:00 -0700 (PDT)     miller@advlaser.com
3627  Fri, 15 Jun 2001 13:23:55 -0700 (PDT)  amelia.alder@enron.com

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 to  \
1546                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             klay@enron.com, neuhaus@3di.com, jtt@jttrotter.com
4223  fredinvt@juno.com, akinpa@email.msn.com, bwall@copcp.com, \n\twilliamhjordan@mindspring.com, jansson@mindspring.com, \n\tjudgegyro@yahoo.com, golfnbud@aol.com, chuck.paul@a-closer-look.com, \n\thandshohl@eudoramail.com, craigd9561@aol.com, \n\tchristop@netcomuk.co.uk, ccoburn@themissionbank.com, \n\tshackleton@worldnet.att.net, boardwalk@iquest.net, dfullert@nmh.org, \n\tfroby@holmesmurphy.com, wgander@twa.com, \n\tjohn_grumbles@berryplastics.com, hbrunette@earthlink.net, \n\tharris@wheelerads.com, jdent@mmcable.com, jglass@mmind.net, \n\tjepetree@bellsouth.net, jowen9653@aol.com, jskilli@enron.com, \n\tjawallace12050@aol.com, jstorthz@flash.net, miller@advlaser.com, \n\tkcason@flash.net, kstewart@ctcua.org, \n\tleland.white@energyspectrum.com, markpa@gateway.net, \n\tmbaddour@msn.com, hutchathoh@aol.com, rrossell@angiodynamics.com, \n\tsamuraimai@aol.com, jimfulrich@aol.com, sogborn@goiac.com, \n\thosman@flash.net, rharman@bass-associates.com, bensons3@airmail.net, \n\tpwm1950@aol.com, boethia@hotmail.com, azaremba@fzci.net, \n\twthom25746@aol.com, hosman@eskridge.net
3627                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Unknown Recipient

                subject  \
1546           Fwd: Fw:
4223  RE: tent and more
3627     TAKE A BOW !!!

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          body  \
1546  I though you might like to read this one.    John\nReturn-path: <Shirleych@aol.com>\nFrom: Shirleych@aol.com\nFull-name: Shirleych\nMessage-ID: <2f.bdb2a81.271d0320@aol.com>\nDate: Mon, 16 Oct 2000 21:19:28 EDT\nSubject: Fwd: Fw:\nTo: 229HUCKL574@MSN\nMIME-Version: 1.0\nContent-Type: multipart/mixed; boundary="part2_60.7ceaf3e.271d0320_boundary"\nX-Mailer: Windows AOL sub 13\nReturn-path: <EleMH@aol.com>\nFrom: EleMH@aol.com\nFull-name: EleMH\nMessage-ID: <54.aa7f6cd.271ce8d9@aol.com>\nDate: Mon, 16 Oct 2000 19:27:21 EDT\nSubject: Fwd: Fw:\nTo: Shirleych@aol.com, Babsch1221@aol.com, ANNEUTSLER@aol.com, \npifalee@earthlink.net, ggjr@hctc.net, hatfield@mail.utexas.edu, \nVMcgrew820@aol.com, Betsyreichert@aol.com, BSetrakian@aol.com, \ndiwar@flash.net, LWWS@aol.com, chuchusmith@ctesc.net, DWaltmon70@aol.com\nMIME-Version: 1.0\nContent-Type: multipart/mixed; boundary="part3_60.7ceaf3e.271ce8d9_boundary"\nX-Mailer: AOL for Macintosh sub 28\nReturn-Path: <horns02@ibm.net>\nReceived: from  rly-yb01.mx.aol.com (rly-yb01.mail.aol.com [172.18.146.1]) by \nair-yb01.mail.aol.com (v76_r1.14) with ESMTP; Mon, 16 Oct 2000 09:41:46 -0400\nReceived: from  prserv.net (out4.prserv.net [32.97.166.34]) by \nrly-yb01.mx.aol.com (v76_r1.19) with ESMTP; Mon, 16 Oct 2000 09:41:02 -0400\nReceived: from francesp ([32.100.167.101]) by prserv.net (out4) with \nSMTP          id <20001016133801239035fgo4e>; Mon, 16 Oct 2000 13:38:02 +0000\nFrom: "Frances Pearce" <horns02@ibm.net>\nTo: "Ele Hill" <EleMH@aol.com>\nSubject: Fw:\nDate: Mon, 16 Oct 2000 08:45:24 -0500\nMessage-ID: <01c03777$55dda980$65a76420@francesp>\nMIME-Version: 1.0\nContent-Type: multipart/alternative; \nboundary="----=_NextPart_000_0068_01C0374D.6D07A180"\nX-Priority: 3\nX-MSMail-Priority: Normal\nX-Mailer: Microsoft Outlook Express 4.71.1712.3\nX-MimeOLE: Produced By Microsoft MimeOLE V4.71.1712.3\n?\n-----Original Message-----\nFrom:  \nFrances Pearce <horns02@ibm.net>\nTo: Barb Bunten  \n<Barjobun@aol.com>\nDate:  \nMonday, October 16, 2000 8:43 AM\nIMPRESSIVE LETTER FROM LIZ CHENEY PERRY\nIn this America of  \nours, where the passion for publicity is a disease and\nwhere swarms of  \nfoolish tawdry moths dash with rapture into its consuming\nfire, it was a rare  \ngood fortune that brought to eminence a man so reserved,\nso unassuming, so  \nretiring, so gracious to high and low, and so serene.&quot;\nJudge Learned  \nHand in tribute to Justice Cardozo, 1938.\nHere are some things America  \nshould know about my dad, Dick Cheney.? He\nloves the mountains and  \nrivers and prairies that stretch into forever in\nWyoming.? He is of the  \nAmerican West.? His handshake is firm.? He looks you\nin the  \neye.? His word is his bond.? He is a world class listener, and  \nwhen\nhe talks, it is always worth listening.? I have never known a wiser  \nman.\nTo my three daughters, he is &quot;Papa.&quot;? Watching him with  \nhis granddaughters\nis a great joy.?? My daughters are young and  \ntheir concerns are the concerns\nof little girls -- dolls and play-dough and  \nfirst friends.? He has infinite\ntime for them, as he always has for my  \nsister and me.? He is never rushed,\nnever hurried.? He is supremely  \nkind, loving and patient - listening to\ntheir latest song from school,  \nreading bedtime stories, or teaching them how\nto fish (a lesson Cheneys learn  \nearly). \nHe grew up in Casper, Wyoming in the days when you could ride your  \nbike out\nof town and hunt rabbits on the prairie.? His dad, a World War  \nII veteran,\nwas a career civil servant with the Soil Conservation  \nService.? His mom\nworked as a secretary at Bustard's Funeral Home to  \nmake ends meet.? He\npitched for the local American Legion baseball  \nteam.? He owed much of his\nskill to my grandmother, who had played for  \nthe Syracuse, Nebraska\nBluebirds, a nationally-ranked girls' softball  \nteam.? She caught his pitches\nmany evenings on their front lawn at 505  \nTexas Place.\nHe was the first in his family to graduate from college.?  \nHe built\npowerlines across Wyoming and Colorado to help pay his way.? He  \ncarried a\nticket for six years in the International Brotherhood of Electrical  \nWorkers.\nHe married his high school sweetheart, Lynne, in  \n1964.?? One look at the\ninscriptions they penned in each other's  \nhigh school yearbooks and you know\nthey were as deeply in love at 18 as they  \nare today.? He was the captain of\nthe football team and she was the  \nhomecoming queen.? Getting her elected was\nhis first political  \ncampaign.\nThere have been lots of other campaigns since then.? Despite  \nhis success,\nhe's not a typical politician.? He's not a  \nglad-hander.? He's not a\nfast-talker.? He's not slick.? He is  \nwho he is.? He is real and honest and\ntrue.? \nHe loves this  \ncountry.? He knows how blessed we all are to be Americans.?  \nHe\ntaught my sister and me that we owe everything we have to the brave men  \nand\nwomen who died so that we could be free.? When we were young, he  \ntook us to\nthe battlefields where the Civil War was fought.? He taught  \nus to love\nhistory and to revere this great nation.???  \nServing as Secretary of Defense was the greatest honor of his life.? I  \nhave\nheard him say that this was because of the troops, the men and women of  \nthe\nU.S. military.? I went with him to Arlington National Cemetery the  \nday of\nthe memorial service for the servicemen and women who died in the  \nPersian\nGulf War.?? I stood next to him in the amphitheater with  \nthe families who\nhad lost sons and daughters, husbands and wives, watching as  \nthe military\njets flew overhead in the missing man formation.? It was  \nthe first time I\never saw tears in his eyes. \nThere are cynics today who  \nwould have us believe that no politician is a man\nof honor.? Maybe the  \nlast eight years have done this to us.? I hope not.\nThere are good  \npeople in American politics today; honorable and wise people,\npeople who keep  \ntheir word and inspire us to live lives of goodness and\ntruth.? There  \nare leaders among us.? \nIn Governor Bush and my father, America has the  \nchance to vote for two of\nthese men this Election Day. \nLiz Cheney Perry

In [23]:
df['body_clean'] = df['body_clean'].str.replace(r'^(Hi|Hello|Dear)\s+[A-Z][\w\s\',-]*,?\s+', '', regex=True, flags=re.IGNORECASE)

In [24]:
df.sample(3)

,date,from,to,subject,body,custodian,folder_source,date_clean,body_inspect,body_clean
4938,"Wed, 25 Apr 2001 11:32:00 -0700 (PDT)",joannie.williamson@enron.com,kevinscott@onlinemailbox.net,Re: Information for Jeff Skilling from Kevin Scott,"Confirming 1:00 p.m. meeting on June 12 at the Venetian Resort in Las Vegas.\nThanks,\nJoannie Williamson\n713-345-7774\n""Kevin Scott"" <kevinscott@onlinemailbox.net> on 04/25/2001 04:46:18 PM\nPlease respond to <kevinscott@onlinemailbox.net>\nTo: ""Jeff Skilling"" <jeff.skilling@enron.com>\ncc: ""Sherri Sera"" <sherri.sera@enron.com> \nSubject: Information for Jeff Skilling from Kevin Scott\n?\n?\n?\n?\n?\nApril 25, 2001\n?\n?\n?\nDear Jeff,\n?\nThank you for setting aside time to meet with me.? I have attached my resume \nto help bring you up to date on my career.? \n?\nAs you will see, I have been providing advisory services since 1995.?? During \nthese years, I have done some of my best work.? I am proud of the service \nthat I have rendered as an independent consultant.? \n?\nNow, I feel it is time to move to a new chapter in my career.? I look forward \nto sitting down with you to think through ways to apply my experience, \nintellect and energies to new professional challenges.? I respect you \ntremendously, and wherever the next part of my career may lie, I know that my \nsearch and choice will benefit significantly from your perspective.\n?\nFinally, I am attaching the recommendation to HBS that you wrote in 1981.? I \nfound it during a profoundly challenging period in my life.? Your historic \nwords of support helped me keep fighting and successfully moving forward.\n?\nIf you would like to reach me before our meeting, please call (213) 926-2626 \nor email kevinscott@onlinemailbox.net.? Thank you again.\n?\nSincerely,\n?\n[IMAGE]\n?\nKevin\n?\n?\nAttachments (2)\n - image001.png\n - image002.gif\n - Resume of Kevin Scott.doc\n - Skilling HBS Recommendation.doc\n",skilling-j,sent,2001-04-25 18:32:00+00:00,"Confirming 1:00 p.m. meeting on June 12 at the Venetian Resort in Las Vegas.Thanks,Joannie Williamson713-345-7774""Kevin Scott"" <kevinscott@onlinemailbox.net> on 04/25/2001 04:46:18 PMPlease respond to <kevinscott@onlinemailbox.net>To: ""Jeff Skilling"" <jeff.skilling@enron.com>cc: ""Sherri Sera"" <sherri.sera@enron.com> Subject: Information for Jeff Skilling from Kevin Scott?????April 25, 2001???Dear Jeff,?Thank you for setting aside time to meet with me.? I have attached my resume to help bring you up to date on my career.? ?As you will see, I have been providing advisory services since 1995.?? During these years, I have done some of my best work.? I am proud of the service that I have rendered as an independent consultant.? ?Now, I feel it is time to move to a new chapter in my career.? I look forward to sitting down with you to think through ways to apply my experience, intellect and energies to new professional challenges.? I respect you tremendously, and wherever the next part of my career may lie, I know that my search and choice will benefit significantly from your perspective.?Finally, I am attaching the recommendation to HBS that you wrote in 1981.? I found it during a profoundly challenging period in my life.? Your historic words of support helped me keep fighting and successfully moving forward.?If you would like to reach me before our meeting, please call (213) 926-2626 or email kevinscott@onlinemailbox.net.? Thank you again.?Sincerely,?[IMAGE]?Kevin??Attachments (2) - image001.png - image002.gif - Resume of Kevin Scott.doc - Skilling HBS Recommendation.doc","Confirming 1:00 p.m. meeting on June 12 at the Venetian Resort in Las Vegas.Thanks,Joannie Williamson713-345-7774""Kevin Scott"" <kevinscott@onlinemailbox.net> on 04/25/2001 04:46:18 PMPlease respond to <kevinscott@onlinemailbox.net>To: ""Jeff Skilling"" <jeff.skilling@enron.com>cc: ""Sherri Sera"" <sherri.sera@enron.com> | Subject: | Information for Jeff Skilling from Kevin Scott?????April 25, 2001???Dear Jeff,?Thank you for setting aside time to meet with me.? I have attached my resume to help bring you up to date on my career.? ?As you will see, I have been providing advisory services since 1995.?? During these years, I have done some of my best work.? I am proud of the service that I have rendered as an independent consultant.? ?Now, I feel it is time to move to a new chapter in my career.? I look forward to sitting down with you to think through ways to apply my experience, intellect and energies to new professional challenges.? I respect you tremendously, and wherever the next part of my career may lie, I know that my search and choice will benefit significantly from your perspective.?Finally, I am attaching the recommendation to HBS that you wrote in 1981.? I found it during a profoundly challenging period in my life.? Your historic words of support helped me keep fighting and successfully moving forward.?If you would like to reach me before our meeting, please call (213) 926-2626 or email kevinscott@onlinemailbox.net.? Thank you again.?Sincerely,?[IMAGE]?Kevin??Attachments (2) - image001.png - image002.gif - Resume of Kevin Scott.doc - Skilling HBS Recommendation.doc"
4205,"Tue, 16 Feb 1999 06:39:00 -0800 (PST)",sherri.reinartz@enron.com,markskilling@hotmail.com,Re:,"Mark, I have a letter here that Jeff would like to mail to you (we still \nhaven't gotten him to use e-mail yet!); however, I don't have an address for \nyou. Please let me know if you have a mailing address in Istanbul, and I'll \nget this in the mail right away. Thank you,\nSherri",skilling-j,discussion_threads,1999-02-16 14:39:00+00:00,"Mark, I have a letter here that Jeff would like to mail to you (we still haven't gotten him to use e-mail yet!); however, I don't have an address for you. Please let me know if you have a mailing address in Istanbul, and I'll get this in the mail right away. Thank you,Sherri","Mark, I have a letter here that Jeff would like to mail to you (we still haven't gotten him to use e-mail yet!); however, I don't have an address for you. Please let me know if you have a mailing address in Istanbul, and I'll get this in the mail right away. Thank you,Sherri"
4001,"Wed, 9 May 2001 01:37:00 -0700 (PDT)",steven.bailey@enron.com,jeff.skilling@enron.com,JPMorganChase Bank,"Jeff, \nMy sister is a Vice President for JPMorgan Chase Bank, and she supervises \nconstruction and management of new buildings in Texas. She sent me the \nfollowing note regarding Enron Energy Services' handling of their utility \nbills:\n""On another note: Enron handles the utility bills for JPMorganChase Bank on\na national basis, including Texas. We are building a call center in San\nAntonio, and the City of San Antonio (municipal electric) wants to charge\nus a $50,000 deposit for new power because 11 out of the last 12 payments\nmade by Enron have been late, and late fees have been paid. I am now going\nto do an analysis on all of my regions. I would like a local Enron\ncontact, if one exists. Any ideas?""\nWhom in Enron should I tell her to contact?\nThanks,\nSteve Bailey\nEnron Global E&P, Inc.\n713-646-7865",skilling-j,discussion_threads,2001-05-09 08:37:00+00:00,"Jeff, My sister is a Vice President for JPMorgan Chase Bank, and she supervises construction and management of new buildings in Texas. She sent me the following note regarding Enron Energy Services' handling of their utility bills:""On another note: Enron handles the utility bills for JPMorganChase Bank ona national basis, including Texas. We are building a call center in SanAntonio, and the City of San Antonio (municipal electric) wants to chargeus a $50,000 deposit for new power because 11 out of the last 12 paymentsmade by Enron have been late, and late fees have been paid. I am now goingto do an analysis on all of my regions. I would like a local Enroncontact, if one exists. Any ideas?""Whom in Enron should I tell her to contact?Thanks,Steve BaileyEnron Global E&P, Inc.713-646-7865","Jeff, My sister is a Vice President for JPMorgan Chase Bank, and she supervises construction and management of new buildings in Texas. She sent me the following note regarding Enron Energy Services' handling of their utility bills:""On another note: Enron handles the utility bills for JPMorganChase Bank ona national basis, including Texas. We are building a call center in SanAntonio, and the City of San Antonio (municipal electric) wants to chargeus a $50,000 deposit for new power because 11 out of the last 12 paymentsmade by Enron have been late, and late fees have been paid. I am now goingto do an analysis on all of my regions. I would like a local Enroncontact, if one exists. Any ideas?""Whom in Enron should I tell her to contact?Thanks,Steve BaileyEnron Global E&P, Inc.713-646-7865"

In [25]:
df_vo2 = df[['from', 'to', 'subject', 'date_clean', 'custodian', 'folder_source', 'body_clean']]
df_vo2 = df_vo2.rename(columns={'date_clean':'date'})

In [26]:
df_vo2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2476 entries, 156 to 5166
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   from           2476 non-null   object
 1   to             2476 non-null   object
 2   subject        2476 non-null   object
 3   date           2476 non-null   datetime64[ns, UTC]
 4   custodian      2476 non-null   object
 5   folder_source  2476 non-null   object
 6   body_clean     2476 non-null   object
dtypes: datetime64[ns, UTC](1), object(6)
memory usage: 154.8+ KB

### Summary

In [27]:
print(f"Unique Emails: {len(df)}")
print(f"Unknown Recipients: {(df['to'] == 'Unknown Recipient').sum()}")

Unique Emails: 2476
Unknown Recipients: 186

In [28]:
df_vo2.to_csv("clean_emails.csv", index=False)