### Importing Packages and Loading Data

In [1]:
import pandas as pd
import os
from email.parser import Parser

In [2]:
POI = ['lay-k', 'skilling-j']
folders = ['sent', 'deleted_items', 'discussion_threads', 'notes_inbox']
mdir = r"C:\Users\AlexaJohnston\Springboard\Enron_Investigation_Capstone\Enron_Investigation"
email_data = []

In [3]:
for person in POI: #for each person in the list POI
    person_path = os.path.join(mdir, person) #create a single path from the main repo to the persons in POI
    for folder in os.listdir(person_path): #create a list of the subfolder for each person
        if any(key in folder.lower() for key in folders): #if any word in a person's folder matches a word in folders
            folder_path = os.path.join(person_path, folder) #look at every file inside the folders that match the words i folders
            for file in os.listdir(folder_path): #for every file in folder path create a list of files
                file_path = os.path.join(folder_path, file) #join the path for the folder with the file
                if os.path.isfile(file_path): #check to make sure each item in file path is a file
                    with open(file_path, 'r', errors='ignore') as f: #Open and read every file, regardless of errors
                        msg = Parser().parsestr(f.read()) #decodes the text into an email format
                        email_data.append({ #creates a dictionary of the fields
                            'date': msg['Date'], 
                            'from': msg['From'],
                            'to': msg['To'], 
                            'subject': msg['Subject'], 
                            'body': msg.get_payload(), 
                            'custodian': person, 
                            'folder_source': folder
                        })
df = pd.DataFrame(email_data) #makes the dictionary into a dataframe
print(f"Success! Captured {len(df)} high-value emails.")

Success! Captured 5359 high-value emails.

### Data Overview

In [4]:
df.head()

,date,from,to,subject,body,custodian,folder_source
0,"Wed, 30 Jan 2002 11:06:10 -0800 (PST)",grnthumb@ipa.netf,klay@enron.com,Demand Ken Lay Donate Proceeds from Enron Stoc...,"Linda Brunner\n12335 S. 2225 Rd.\nStockton, MO...",lay-k,deleted_items
1,"Wed, 30 Jan 2002 11:39:03 -0800 (PST)",avanleunen@msn.com,klay@enron.com,Demand Ken Lay Donate Proceeds from Enron Stoc...,"alice van leunen\n13631 NE Kinney Rd\nNewberg,...",lay-k,deleted_items
2,"Wed, 30 Jan 2002 11:42:03 -0800 (PST)",comet@starshaper.com,klay@enron.com,Demand Ken Lay Donate Proceeds from Enron Stoc...,John-Paul Goorjian\ncomet@starshaper.com\n\nTo...,lay-k,deleted_items
3,"Wed, 30 Jan 2002 09:57:08 -0800 (PST)",manastassatos@randomhouse.com,klay@enron.com,Demand Ken Lay Donate Proceeds from Enron Stoc...,Marietta Anastassatos\n435 Highland Ave\nPalis...,lay-k,deleted_items
4,"Wed, 30 Jan 2002 09:57:10 -0800 (PST)",kmitchel@coba.usf.edu,klay@enron.com,Demand Ken Lay Donate Proceeds from Enron Stoc...,Kimberly Mitchell\n1906 E. Linda Street\nPlant...,lay-k,deleted_items

In [5]:
df.tail()

,date,from,to,subject,body,custodian,folder_source
5354,"Wed, 12 Apr 2000 04:40:00 -0700 (PDT)",sherri.sera@enron.com,maktay@superonline.com,Hi...,"Metin,\n\nGreat to hear from you. Believe it ...",skilling-j,_sent_mail
5355,"Mon, 10 Apr 2000 10:52:00 -0700 (PDT)",sherri.sera@enron.com,annb@redstonegrp.com,RE: Message from Gary Stein,Ugh! :-) Just kidding...I figured it would be ...,skilling-j,_sent_mail
5356,"Mon, 10 Apr 2000 10:38:00 -0700 (PDT)",sherri.sera@enron.com,annb@redstonegrp.com,RE: Message from Gary Stein,I shall be there. Just let me know what time ...,skilling-j,_sent_mail
5357,"Mon, 10 Apr 2000 10:05:00 -0700 (PDT)",sherri.sera@enron.com,annb@redstonegrp.com,Re: Message from Gary Stein,"Ann, I haven't heard from you with regard to w...",skilling-j,_sent_mail
5358,"Fri, 7 Apr 2000 10:11:00 -0700 (PDT)",sherri.sera@enron.com,chuck.paul@a-closer-look.com,Re: Fw:,"Dear Mr. Paul,\n\nI'm writing on behalf of Jef...",skilling-j,_sent_mail

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5359 entries, 0 to 5358
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           5359 non-null   object
 1   from           5359 non-null   object
 2   to             5104 non-null   object
 3   subject        5359 non-null   object
 4   body           5359 non-null   object
 5   custodian      5359 non-null   object
 6   folder_source  5359 non-null   object
dtypes: object(7)
memory usage: 293.2+ KB

In [7]:
df['custodian'].value_counts()

custodian
lay-k         3375
skilling-j    1984
Name: count, dtype: int64

In [8]:
df[df['custodian'] == 'skilling-j']['from'].value_counts().head(10)

from
sherri.sera@enron.com            466
joannie.williamson@enron.com      99
jeff.skilling@enron.com           87
40enron@enron.com                 70
markskilling@hotmail.com          51
fredinvt@juno.com                 41
sherri.reinartz@enron.com         36
katherine.brown@enron.com         31
lisa.connolly@enron.com           26
enron.announcements@enron.com     25
Name: count, dtype: int64

In [9]:
df[df['custodian'] == 'lay-k']['from'].value_counts().head(10)

from
rosalee.fleming@enron.com        595
leonardo.pacheco@enron.com        52
brown_mary_jo@lilly.com           46
savont@email.msn.com              44
tori.wells@enron.com              41
katherine.brown@enron.com         30
elizabeth.davis@compaq.com        29
rob.bradley@enron.com             20
enron.announcements@enron.com     20
lizard_ar@yahoo.com               18
Name: count, dtype: int64

### Converting date column to datetime

In [10]:
df['date'].head()

0    Wed, 30 Jan 2002 11:06:10 -0800 (PST)
1    Wed, 30 Jan 2002 11:39:03 -0800 (PST)
2    Wed, 30 Jan 2002 11:42:03 -0800 (PST)
3    Wed, 30 Jan 2002 09:57:08 -0800 (PST)
4    Wed, 30 Jan 2002 09:57:10 -0800 (PST)
Name: date, dtype: object

In [11]:
df['date_clean'] = pd.to_datetime(df['date'], utc=True)

C:\Users\AlexaJohnston\AppData\Local\Temp\ipykernel_31468\1452036759.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date_clean'] = pd.to_datetime(df['date'], utc=True)

In [12]:
df = df[(df['date_clean'].dt.year >= 1998) & (df['date_clean'].dt.year <= 2001)]

In [13]:
df.head()

,date,from,to,subject,body,custodian,folder_source,date_clean
156,"Tue, 13 Nov 2001 11:14:52 -0800 (PST)",ohi_supporters@operationhope.org,klay@enron.com,The Latest Edition of Operation HOPE Inc.'s El...,\n \nHere It Is !!! \n[IMAGE]\nor copy and pa...,lay-k,deleted_items,2001-11-13 19:14:52+00:00
158,"Mon, 26 Nov 2001 17:37:47 -0800 (PST)",djtheroux@independent.org,lighthouse@independent.org,"THE LIGHTHOUSE: November 26, 2001","THE LIGHTHOUSE\n""Enlightening Ideas for Public...",lay-k,deleted_items,2001-11-27 01:37:47+00:00
1126,"Mon, 2 Aug 1999 08:33:00 -0700 (PDT)",ggalata@enron.co.uk,kenneth.lay@enron.com,Franco Bernabe's tel number,"Ken,\n\nI finally found Franco Bernabe's work ...",lay-k,discussion_threads,1999-08-02 15:33:00+00:00
1127,"Thu, 19 Aug 1999 02:18:00 -0700 (PDT)",rosalee.fleming@enron.com,expense.report@enron.com,Approval of Jeff Skilling's Expense Report,Kenneth Lay has approved the attached expense ...,lay-k,discussion_threads,1999-08-19 09:18:00+00:00
1128,"Mon, 21 Aug 2000 02:36:00 -0700 (PDT)",corry.bentley@enron.com,kenneth.lay@enron.com,Sacrifice,"Here in my group, and all over Enron, I see pe...",lay-k,discussion_threads,2000-08-21 09:36:00+00:00

In [14]:
df.tail()

,date,from,to,subject,body,custodian,folder_source,date_clean
5354,"Wed, 12 Apr 2000 04:40:00 -0700 (PDT)",sherri.sera@enron.com,maktay@superonline.com,Hi...,"Metin,\n\nGreat to hear from you. Believe it ...",skilling-j,_sent_mail,2000-04-12 11:40:00+00:00
5355,"Mon, 10 Apr 2000 10:52:00 -0700 (PDT)",sherri.sera@enron.com,annb@redstonegrp.com,RE: Message from Gary Stein,Ugh! :-) Just kidding...I figured it would be ...,skilling-j,_sent_mail,2000-04-10 17:52:00+00:00
5356,"Mon, 10 Apr 2000 10:38:00 -0700 (PDT)",sherri.sera@enron.com,annb@redstonegrp.com,RE: Message from Gary Stein,I shall be there. Just let me know what time ...,skilling-j,_sent_mail,2000-04-10 17:38:00+00:00
5357,"Mon, 10 Apr 2000 10:05:00 -0700 (PDT)",sherri.sera@enron.com,annb@redstonegrp.com,Re: Message from Gary Stein,"Ann, I haven't heard from you with regard to w...",skilling-j,_sent_mail,2000-04-10 17:05:00+00:00
5358,"Fri, 7 Apr 2000 10:11:00 -0700 (PDT)",sherri.sera@enron.com,chuck.paul@a-closer-look.com,Re: Fw:,"Dear Mr. Paul,\n\nI'm writing on behalf of Jef...",skilling-j,_sent_mail,2000-04-07 17:11:00+00:00

### Handling duplicates

In [15]:
count = len(df) 
df = df.drop_duplicates(subset=['date', 'from', 'subject', 'body'])
count_2 = len(df) 
print(f"Removed {count - count_2} duplicate emails.")

Removed 1754 duplicate emails.

### Handling missing data

In [16]:
df['to'].isnull().sum()

np.int64(186)

In [17]:
missing_to = df[df['to'].isnull()]
print(missing_to['folder_source'].value_counts())

folder_source
deleted_items         108
discussion_threads     73
notes_inbox             5
Name: count, dtype: int64

In [18]:
import numpy as np 
df['to'] = df['to'].replace(r'^\s*$', np.nan, regex=True)
df['to'] = df['to'].fillna('Unknown Recipient')

### Normalizing body

In [19]:
pd.set_option('display.max_colwidth', None)
df['body'].sample(5)

1279                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Ken,\n\nI hope things are well with you.\n\nI've taken on in the last year of my 6 year term the regents' chairmanship\nand so I am busy working on how to help further accelerate the good things\nthat have occurred since we brought Art and his team to Houston.  In this\nlight, I read the recent article in the Wall Street Journal suggesting that\nthe Kuht-TV spectrum allotment includes substantial unused bandwidth which\nwe are legally permitted to lease to the private sector.  The Journal, based\non the recent UK auction, extrapolated the overall worth of the bandwidth at\n$160 billion.  Needless to say, if we could realize a small fraction of\nthat, for something from which we currently derive nothing, it could be a\nhuge boost to our efforts to obtain the additional funding we need as we\nmove to Tier One status.\n\nSince Enron is the leader in the market for bandwidth, I was hoping you or\nsomeone at Enron could give us some advice on what we own, its value, if\nany, and how we might think about realizing on any such value.  From Enron's\nperspective, perhaps there is a niche market for Enron to make by helping\norganize educational institutions that own such bandwidth to exploit the\nvalue of that asset.\n\nAny thoughts or suggestions would be greatly appreciated.\n\nBest regards.\n\nGary\n
3439                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Are you well informed?  Restructuring Today readers got the story below\nlast week.  They've also read interviews with Salt River Project's Dick\nSilverman, Dennis Bakke from AES Corp, Williams' Keith Bailey and Erle\nNye of TXU, to name just a few, in the last month.  Interviews coming up\ninclude Chuck Watson from Dynegy, Sempra's Steven Baum and Alan Raymond\nof Shell Energy.  Restructuring Today tells what the CEOs making the big\ndecisions are thinking and planning on.\n\nFERC RTO bombshell\n\nEnron's Kean, Skilling\nsee big impact on\nretail markets\n---\nWholesale grid to be\n90% open in 2-3 years\n\nEnron Chief of Staff Steve Kean "has been actively involved in getting\nthis stuff done," said CEO Jeff Skilling in introducing Kean to a\nconference call last week.\n     Today's wholesale power market, Enron finds is only about 20-25%\nopen.\n     "This is going to push for something close to 100%," Kean forecast\nbut he wants to see how FERC deals with public power first.\n     "It's going to be a significant, a significant expansion of the\nindustrial market," he predicted, "to 80 or 90% levels within a\nrelatively short period of time."\n     As Kean reads FERC, "they appear to be getting rid of pancaking of\nrates ... We're going to have 100 potential supply sources we're going\nto be able to put in touch with thousands of markets.\n     "It's even more significant than simply getting open access tariffs\nacross the individual utility systems.\n     "We're going to be able to move power from where it is to where\nit's needed."  Kean thinks the RTOs will facilitate the opening of\nretail markets.\n     "As we get more workably competitive wholesale markets it's going\nto increase our ability to deliver away from traditional pooling points\nand serve retail energy markets as well.\n     "A huge step forward and a dramatic increase, a multiple increase\nin the investible market," he told analysts.\n     Skilling agreed with Kean's numbers and went a step farther\npredicting the 20% open shift to 90% open will happen in the next two or\nthree years.\n     "We're serving 30,000 sites," Skilling noted.  "We can physically\nget power to only about 20% of those locations given the constrictions\nin the grid and the difficulty of moving across the grid.\n     "This will make it much, much easier to get power much further out\nfrom the market centers where we've been operating today," Skilling\nforecast.\n\nLet Restructuring Today keep you informed.\n\nRestructuring Today provides you with news and analysis.  RT is written\nby veteran energy news analysts.  They don't just write what the news\nis, like most energy-communications newsletters, they tell you what the\nnews means.\n\nSubscribe today and start benefiting from Restructuring Today's special,\nunique focus on the converging energy and communications industries,\nespecially the opening of competitive markets. Simply fax the attached\norder form to 202-298-8210 and you won't miss another vital issue.\n\nThank you,\n\nSeason Hawksley\nMarketing Manager\nUS Publishing\n800-486-820\n202-298-8201\n\nPS -- Please do not hit reply. To subscribe, cancel, change your email\naddress or ask questions please contact customercare@restructuringtoday.com.\n\n\n\n\n\n\n\n\n\n - orderform.pdf
2965    Ken Lay wrote:\n\nMr. Bryce:\n\nI have no suggestions at this time.\n\nKen Lay\n\n\n\n\nToby Bryce <bryce@juno.com> on 03/30/2001 02:37:23 PM\nTo: bryce@juno.com\ncc: kenneth.lay@enron.com \nSubject: Re: Board opportunity\n\n\n\nMr. Lay,\n?\nYour assistant contacted me a couple weeks back with the message that the  \nattached was not an opportunity you could consider at this time.? Thanks  \nvery much, though, for taking a look at it.\n?\nI have one follow-up question for you -- could you recommend another Enron  \nexecutive that might be a candidate for such an opportunity?? \n?\nTo help you answer the question, the company is Juno Online?Services,  \nInc.?(NASDAQ: JWEB), a leading US ISP.? Juno is very interested in  working \nwith (and in advanced-stage discussions with) companies in the energy  \nindustry and working with them on strategic telecommunications and marketing  \npartnerships.\n?\nInformation about Juno is available at "About Juno" on Juno's Web site \nhttp://www.juno.com.? I've also attached an  executive summary to update you \n(or the relevant person at Enron) as to the  current status of Juno's \nbusiness.\n?\nThanks very much for your assistance, and I hope that this message finds  you \nwell.\n?\nBest,\n?\nToby\n?\nExecutive Overview of?Juno --\n\nThe company finished 4Q00 w/ $56MM in cash.? Total net loss for 2001  was \nprojected to be $10-$25MM, as the company focuses on billable services,  \ncontinues to reduce expenses, and looks to develop advertising and other  \nancillary revenue streams.? The company is confident that it can meet  \nor?beat the loss target and made explicit statements that on-hand cash  \nresources are "more than adequate" to get the business profitable.? The  \ncompany has not publicly given a time-line for profitability to maintain  \nflexibility.  \nThe company controls one of the largest dialup subscriber audiences (4MM  \nactive subscribers as of 4Q00, 850K of whom are billable) on the Internet  \ntoday and is the 4th largest US ISP (after AOL, ELNK, and MSN).  \n2000 revenue came in at $114MM, 65% of which was derived from subscription  \nfees and 35% from advertising.? 2001 revenues are expected to come in  \nbetween $100MM-$120MM, with the revenue mix moving toward 80% subscription \nand  20% advertising due to increased focus on billable services and the \nsoft  Internet advertising markets.  \nJuno has announced broadband agreements for its Juno Express product  \ncovering all mainstream broadband transport platforms -- AT&T Broadband,  \nTime Warner Cable, and Comcast (cable); Covad (DSL); Hughes (satellite); and  \nMetricom (wireless).  \nThe company has announced wireless distribution agreements for it's Juno  \nMobile product with Palm and Sprint PCS.? Other agreements are likely to  be \nforthcoming.  \nThe company has powerful propietary technology assets that give it a  \ncompetitive advantage.? The company has launched (internally but not  \npublicly) a new business unit -- Juno Solutions -- to investigate the  \nopportunity to license these technology assets to third parties both  \ndomestically and internationally.?  \nThe Juno Virtual Supercomputer Project represents another example of  Juno's \nefforts to develop ancillary revenue streams.? This distributed  computing \ninitiative aims to leverage unused computer processing power from  Juno's MMs \nof subscribers, aggregating it for sale to biotech, pharmaceutical,  and \ncomputational chemistry firms.? \nhttp://www.juno.com/corp/news/supercomputer.html\n\n\n=============\nToby  Bryce\n(347) 200-0882\nbryce@juno.com\n=============\n?\nOn Wed, 14 Mar 2001 16:52:52 -0500 Toby Bryce <bryce@juno.com> writes:\n> Mr.  Lay,\n> \n> I am contacting you (per instructions of Rosalee) with a  director \n> opportunity with a NASDAQ-listed Internet media firm.?  The NYC-based \n> firm had $114MM in revenue in calendar 2000 and made  strong \n> statements with its most recent (4Q00) earnings statements that  \n> management believes that on-hand cash resources are "more than \n>  adequate" to get the business profitable.? The company is \n>  well-positioned to both survive and profit from the current \n> difficult  market and as such could make for an interesting \n> opportunity for  you.\n> \n> I am working on this recruiting project as an independent  consultant \n> for the company and would be happy to tell you more  specifically \n> about the opportunity should you be interested in  concept.? You can \n> reach me via e-mail at this address (bryce@juno.com) or \n> telephonically at  (347) 200-0882.? \n> \n> I hope that this message finds you well,  and I look forward to \n> hearing from you at your convenience.\n>  \n> Best,\n> \n> Toby\n> \n> =============\n> Toby  Bryce\n> (347) 200-0882\n> bryce@juno.com??? \n?\n\n
3929                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Stan,\n\nPer Jeff's request, I have forwarded the resume you attached to Philippe \nBibi, President & CEO of Enron NetWorks.\n\nJeff would be interested in a tour of the building.  Would if the afternoon \nof May 8, at 3:30 would work for your schedule.  At Jeff's request, I plan on \nincluding Bill Donovan.\n\nThanks,\nJoannie\n\n\n\n\n\nstanmarek@marekbros.com on 03/14/2001 08:49:41 AM\nTo: jeff.skilling@enron.com\ncc:  \n\nSubject: Follow-Up - Brent Larsen\n\n\n\nJeff,\n\nHow's it going in the world of energy?  I enjoy reading about you and your\nadventures. Sounds like you might be having a little fun as well.\n\nAttached is a resume from an acquaintance of mine.  Nice guy and would be\ncredit to anyone's organization.  Thought you  might forward it to\npersonnel.\n\nDon't forget you've got a lifetime warranty on the drywall in your house.\nMy compliments.  Call me if you have any problems.  Also I walked your new\nbuilding last week.  Quite impressive, especially what we're having to\nbuild on a tight schedule.  Should really be nice.  If you'd like a\npersonal tour, let me know.  I'd love to put you in a hardhat and introduce\nyou to the team that's doing all the work.  Would make a great shot for my\nin-house publication and maybe yours as well.\n\nMiss seeing you at our Forum meetings.  WPO is not as much fun as YPO.\nEnjoy it while you can!\n\n-Stan\n----- Forwarded by Stan Marek/MBS on 03/14/01 08:44 AM -----\n\n                    "Brent R. Larsen"\n                    <brent.larsen@redm        To:     \n<stanmarek@marekbros.com>\n                    eteor.com>                cc:\n                                              Subject:     Follow-Up - Brent \nLarsen\n                    02/19/01 05:26 PM\n                    Please respond to\n                    brent.larsen\n\n\n\n\n\nHi Stan:\n\nIt was good to meet you this morning. I've enjoyed working out with Joel;\nhe's a good "kid" and I can certainly relate to his Midwest roots and Iowa\nState background. I grew up on a grain/livestock farm in Gladbrook, Iowa, a\ntown of under 1,000 people, and did my BS at Iowa State and MBA at Kansas\nUniversity.\n\nI'm currently working as Director, Business Development at RedMeteor.com,\nan\ninternet-based energy brokerage company. We compete against Altra Energy,\nEnronOnline, InterContinentalExchange and HoustonStreet. We started with\n$22\nmillion in venture capital, but need an additional infusion of capital to\nbuild out our business model. I think it's going to be difficult for us to\nattract additional funding in this climate, so I'm interested in making a\nmove to another employer when I find the right fit.\n\nAs I mentioned this morning, I've been talking with Conoco recently (my\nprevious employer for 9 years) as well as Enron's Broadband Services group.\nI'm looking for a Houston-based business development position that would\nbuild on my eCommerce experience at RedMeteor or my oil & gas pipeline\noperations background. I've also met with Reliant Energy recently although\nI\nunderstand they've suspended hiring in their trading/eCommerce groups due\nto\nthe California crisis.\n\nAny suggestions you would have would be appreciated. Thanks for your time.\n\nBrent Larsen\nW: 281/243-6527\nC: 832/724-7666\n\n\n(See attached file: B Larsen 2-16-01.doc)\n\n - B Larsen 2-16-01.doc\n\n

In [20]:
import re
df['body'] = df['body'].str.replace(r'\r\n|\r', '\n', regex=True)
df['body'] = df['body'].str.replace(r'\n+', '\n', regex=True)
df['body_inspect'] = df['body'].str.replace('\n', '')
print(df['body_inspect'].sample(1).iloc[0])

For employees who have not been through the PRC/PEP process before, please be advised that there will be PRC/ PEP training available.  Please attend one of the training sessions below: PRC/PEP Employee & Supervisor TrainingDate: October 30,2000Place: Hyatt, AboretumSession I: 9:00- 11:00 a.m.Session II: 2:00- 4:00 p.m.Date: October 31,2000Place: EB49C3Session I: 9:00- 11:00 a.m.Session II: 2:00- 4:00 p.m.In the next few days, all employees will receive PRC/PEP training material in the mail.  If you have utilized the PEP system before, then attendance for the training sessions are optional.  The new intranet interface should make the PEP system more user friendly and faster.  Please contact Jennifer Jordan at ext: 3-7554, if you have any questions concerning training materials or classes

In [21]:
df['body_clean'] = df['body_inspect']
df['body_clean'] = df['body_clean'].str.replace(r'(?i)(^|\s)(From:)', r'\1| \2', regex=True)
df['body_clean'] = df['body_clean'].str.replace(r'(?i)(^|\s)(To:)', r'\1| \2', regex=True)
df['body_clean'] = df['body_clean'].str.replace(r'(?i)(^|\s)(Subject:)', r'\1| \2', regex=True)
df['body_clean'] = df['body_clean'].str.replace(r'(?i)(Subject:.*?)(?=\s|$)', r'\1 |', regex=True)
df['body_clean'] = df['body_clean'].str.strip()
print(df['body_clean'].sample(1).iloc[0])

Ken, Jeff and Louise,Below please find links for the Multimedia version of the Harvard cases completed in final form last month.  The text of the multimedia case is the same as that previously forwarded.  I have reviewed these multimedia cases and they are very cool!I will be forwarding Releases to each of you for signature.  Please return the releases as soon as possible as Meg Wozny at Harvard, with whom I've been working on these for the past few months, is leaving HBS at the end of June--I'd like for her to have the satisfaction of finalizing this project before she leaves.Harvard reports that these cases are best sellers!  Also, we enjoyed an "Enron day"at Harvard April 26th; it received such rave reviews that Harvard has requested a similar event for this summer.Thanks to all of you for your participation and help!--Christie.---------------------- Forwarded by Christie Patrick/HOU/ECT on 06/18/2001 05:34 PM ---------------------------Meg Wozny <mwozny@hbs.edu> on 06/11/2001 10:10:40 AMTo:	Christie.Patrick@enron.comcc:	 | Subject: |	Multimedia Harvard Cases http://hbsdev.hbs.edu:8008/9-301-064/http://hbsdev.hbs.edu:8008/9-301-085/

In [22]:
df.sample(3)

,date,from,to,subject,body,custodian,folder_source,date_clean,body_inspect,body_clean
2930,"Tue, 8 May 2001 05:43:00 -0700 (PDT)",rosalee.fleming@enron.com,hvg@carbon.cudenver.edu,Re: Request for Bios,"Here is Mr. Lay's bio.\nRosalee\n""Heidi VanGenderen"" <hvg@carbon.cudenver.edu> on 05/08/2001 10:46:40 AM\nPlease respond to <hvg@carbon.cudenver.edu>\nTo: \ncc: ""Marshall Kaplan (E-mail)"" <mkaplan@carbon.cudenver.edu>, ""'Sue Green'"" \n<s1green@carbon.cudenver.edu>, ""Tom McCoy (E-mail)"" \n<tmccoy@carbon.cudenver.edu> \nSubject: Request for Bios\nHello All:\nWe are looking forward to the May 22-23 Forum on Securing the Energy Future\nof the Western United States.\nIf you wish to have a paragraph-long bio included in the Forum notebook,\nplease respond to this e-mail by sending your bio. Feel free to fax one, if\nthat's easier, as well.\nPlease don't hesitate to contact us with any questions or comments.\nThanks very much,\nHeidi VanGenderen, Senior Associate\nWirth Chair in Environmental and\nCommunity Development Policy\nInstitute for Policy Research and Implementation\nUniversity of Colorado-Denver\n1445 Market Street, Suite 350\nDenver, CO 80202-1727\nTel - 303-820-5676\nFax - 303-534-8774\n",lay-k,sent,2001-05-08 12:43:00+00:00,"Here is Mr. Lay's bio.Rosalee""Heidi VanGenderen"" <hvg@carbon.cudenver.edu> on 05/08/2001 10:46:40 AMPlease respond to <hvg@carbon.cudenver.edu>To: cc: ""Marshall Kaplan (E-mail)"" <mkaplan@carbon.cudenver.edu>, ""'Sue Green'"" <s1green@carbon.cudenver.edu>, ""Tom McCoy (E-mail)"" <tmccoy@carbon.cudenver.edu> Subject: Request for BiosHello All:We are looking forward to the May 22-23 Forum on Securing the Energy Futureof the Western United States.If you wish to have a paragraph-long bio included in the Forum notebook,please respond to this e-mail by sending your bio. Feel free to fax one, ifthat's easier, as well.Please don't hesitate to contact us with any questions or comments.Thanks very much,Heidi VanGenderen, Senior AssociateWirth Chair in Environmental andCommunity Development PolicyInstitute for Policy Research and ImplementationUniversity of Colorado-Denver1445 Market Street, Suite 350Denver, CO 80202-1727Tel - 303-820-5676Fax - 303-534-8774","Here is Mr. Lay's bio.Rosalee""Heidi VanGenderen"" <hvg@carbon.cudenver.edu> on 05/08/2001 10:46:40 AMPlease respond to <hvg@carbon.cudenver.edu>To: cc: ""Marshall Kaplan (E-mail)"" <mkaplan@carbon.cudenver.edu>, ""'Sue Green'"" <s1green@carbon.cudenver.edu>, ""Tom McCoy (E-mail)"" <tmccoy@carbon.cudenver.edu> | Subject: | Request for BiosHello All:We are looking forward to the May 22-23 Forum on Securing the Energy Futureof the Western United States.If you wish to have a paragraph-long bio included in the Forum notebook,please respond to this e-mail by sending your bio. Feel free to fax one, ifthat's easier, as well.Please don't hesitate to contact us with any questions or comments.Thanks very much,Heidi VanGenderen, Senior AssociateWirth Chair in Environmental andCommunity Development PolicyInstitute for Policy Research and ImplementationUniversity of Colorado-Denver1445 Market Street, Suite 350Denver, CO 80202-1727Tel - 303-820-5676Fax - 303-534-8774"
5034,"Thu, 2 Aug 2001 14:44:40 -0700 (PDT)",jeff.skilling@enron.com,mary.clark@enron.com,FW: E-Mail to Office of the Chairman,"\n -----Original Message-----\nFrom: \tSkilling, Jeff \nSent:\tWednesday, August 01, 2001 12:17 PM\nTo:\tFernandez, Fernando\nSubject:\tE-Mail to Office of the Chairman\nFernando,\nI did receive your e-mails and wanted to assure you that your concerns are being dealt with. \nThank you,\nJeff",skilling-j,sent_items,2001-08-02 21:44:40+00:00,"-----Original Message-----From: \tSkilling, Jeff Sent:\tWednesday, August 01, 2001 12:17 PMTo:\tFernandez, FernandoSubject:\tE-Mail to Office of the ChairmanFernando,I did receive your e-mails and wanted to assure you that your concerns are being dealt with. Thank you,Jeff","-----Original Message-----From: \tSkilling, Jeff Sent:\tWednesday, August 01, 2001 12:17 PMTo:\tFernandez, FernandoSubject: |\tE-Mail to Office of the ChairmanFernando,I did receive your e-mails and wanted to assure you that your concerns are being dealt with. Thank you,Jeff"
4943,"Wed, 19 Apr 2000 02:34:00 -0700 (PDT)",sherri.sera@enron.com,kskilling@ehshouston.org,RE: Lunch today,"That's the one. Have fun! SRS\n""Skilling, Kristin"" <kskilling@EHSHOUSTON.ORG> on 04/19/2000 09:01:55 AM\nTo: ""'Jeff.Skilling@enron.com'"" <Jeff.Skilling@enron.com>\ncc: \nSubject: RE: Lunch today\nHey Sherri- I got your email and that sounds great. That is the one on Post\nOak right??? Thanks so much!!! Have a great day.\n~ks~\n -----Original Message-----\n From: Jeff.Skilling@enron.com\n[mailto:Jeff.Skilling@enron.com]\n Sent: Wednesday, April 19, 2000 8:27 AM\n To: kskilling@ehshouston.org\n Subject: Lunch today\n Importance: High\n Hi, Kristin,\n Your Dad asked me to let you know that he got your message.\nHe would like\n to meet you at Maggiones (the place you two met for lunch\nthe first time).\n I'm making a reservation for you guys in his name at 1:00\np.m.\n Would you please reply to this e-mail so I know you got it?\nThanks,\n Kristin, and have a nice lunch.\n Sherri\n",skilling-j,sent,2000-04-19 09:34:00+00:00,"That's the one. Have fun! SRS""Skilling, Kristin"" <kskilling@EHSHOUSTON.ORG> on 04/19/2000 09:01:55 AMTo: ""'Jeff.Skilling@enron.com'"" <Jeff.Skilling@enron.com>cc: Subject: RE: Lunch todayHey Sherri- I got your email and that sounds great. That is the one on PostOak right??? Thanks so much!!! Have a great day.~ks~ -----Original Message----- From: Jeff.Skilling@enron.com[mailto:Jeff.Skilling@enron.com] Sent: Wednesday, April 19, 2000 8:27 AM To: kskilling@ehshouston.org Subject: Lunch today Importance: High Hi, Kristin, Your Dad asked me to let you know that he got your message.He would like to meet you at Maggiones (the place you two met for lunchthe first time). I'm making a reservation for you guys in his name at 1:00p.m. Would you please reply to this e-mail so I know you got it?Thanks, Kristin, and have a nice lunch. Sherri","That's the one. Have fun! SRS""Skilling, Kristin"" <kskilling@EHSHOUSTON.ORG> on 04/19/2000 09:01:55 AMTo: ""'Jeff.Skilling@enron.com'"" <Jeff.Skilling@enron.com>cc: | Subject: | RE: Lunch todayHey Sherri- I got your email and that sounds great. That is the one on PostOak right??? Thanks so much!!! Have a great day.~ks~ -----Original Message----- | From: Jeff.Skilling@enron.com[mailto:Jeff.Skilling@enron.com] Sent: Wednesday, April 19, 2000 8:27 AM | To: kskilling@ehshouston.org | Subject: | Lunch today Importance: High Hi, Kristin, Your Dad asked me to let you know that he got your message.He would like to meet you at Maggiones (the place you two met for lunchthe first time). I'm making a reservation for you guys in his name at 1:00p.m. Would you please reply to this e-mail so I know you got it?Thanks, Kristin, and have a nice lunch. Sherri"

In [23]:
df['body_clean'] = df['body_clean'].str.replace(r'^(Hi|Hello|Dear)\s+[A-Z][\w\s\',-]*,?\s+', '', regex=True, flags=re.IGNORECASE)

In [24]:
df['body_clean'] = df['body_clean'].str.replace(r'(_{2,}|-{2,}|Best regards,|Regards,|Thank you,|Thanks,|Sincerely,|Cheers,).*$', '', regex=True, flags=re.IGNORECASE|re.DOTALL)
df['body_clean'] = df['body_clean'].str.strip()

In [25]:
df['body_clean'] = df['body_clean'].str.replace('=', '', regex=True, flags=re.IGNORECASE)

In [26]:
df.sample(3)

,date,from,to,subject,body,custodian,folder_source,date_clean,body_inspect,body_clean
3596,"Wed, 20 Jun 2001 13:01:17 -0700 (PDT)",40enron@enron.com,Unknown Recipient,ATTENTION OUTLOOK USERS - EMAIL POLICIES,"\nTo date, we have migrated approximately 7300 users from Lotus Notes to Microsoft Outlook in North America. As we bring this migration to a close over the coming months, we would like to remind you, the Outlook user, of a few very important policies.\n1. As Corporate policy states, Global Technology Infrastructure is monitoring the use of Internet eMail, which includes sending mail to and receiving mail from the Internet.\n2. There is an eMail retention policy, which provides as follows:\nMessage Location\tMaximum Retention\nInbox\t\t30 days\nSent Mail Folder\t30 days\nTrash\t\tRollover from Inbox for one day\nFolders\t\tAll eMail messages placed in folders will be destroyed after one calendar year\nThere will be no exceptions to this policy.\n3. We will be including a legal trailer or disclaimer message to the bottom of every outgoing Internet eMail. The legal disclaimer text is as follows:\n""This e-mail is the property of Enron Corp. and/or its relevant affiliate and may contain confidential and privileged material for the sole use of the intended recipient (s). Any review, use, distribution or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive for the recipient), please contact the sender or reply to Enron Corp. at enron.messaging.administration@enron.com and delete all copies of the message. This e-mail (and any attachments hereto) are not intended to be an offer (or an acceptance) and do not create or evidence a binding and enforceable contract between Enron Corp. (or any of its affiliates) and the intended recipient or any other party, and may not be relied on by anyone as the basis of a contract by estoppel or otherwise. Thank you. ""\t\t\nFor questions, please call the Resolution Center at ext. 31411.\n",skilling-j,deleted_items,2001-06-20 20:01:17+00:00,"To date, we have migrated approximately 7300 users from Lotus Notes to Microsoft Outlook in North America. As we bring this migration to a close over the coming months, we would like to remind you, the Outlook user, of a few very important policies.1. As Corporate policy states, Global Technology Infrastructure is monitoring the use of Internet eMail, which includes sending mail to and receiving mail from the Internet.2. There is an eMail retention policy, which provides as follows:Message Location\tMaximum RetentionInbox\t\t30 daysSent Mail Folder\t30 daysTrash\t\tRollover from Inbox for one dayFolders\t\tAll eMail messages placed in folders will be destroyed after one calendar yearThere will be no exceptions to this policy.3. We will be including a legal trailer or disclaimer message to the bottom of every outgoing Internet eMail. The legal disclaimer text is as follows:""This e-mail is the property of Enron Corp. and/or its relevant affiliate and may contain confidential and privileged material for the sole use of the intended recipient (s). Any review, use, distribution or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive for the recipient), please contact the sender or reply to Enron Corp. at enron.messaging.administration@enron.com and delete all copies of the message. This e-mail (and any attachments hereto) are not intended to be an offer (or an acceptance) and do not create or evidence a binding and enforceable contract between Enron Corp. (or any of its affiliates) and the intended recipient or any other party, and may not be relied on by anyone as the basis of a contract by estoppel or otherwise. Thank you. ""\t\tFor questions, please call the Resolution Center at ext. 31411.","To date, we have migrated approximately 7300 users from Lotus Notes to Microsoft Outlook in North America. As we bring this migration to a close over the coming months, we would like to remind you, the Outlook user, of a few very important policies.1. As Corporate policy states, Global Technology Infrastructure is monitoring the use of Internet eMail, which includes sending mail to and receiving mail from the Internet.2. There is an eMail retention policy, which provides as follows:Message Location\tMaximum RetentionInbox\t\t30 daysSent Mail Folder\t30 daysTrash\t\tRollover from Inbox for one dayFolders\t\tAll eMail messages placed in folders will be destroyed after one calendar yearThere will be no exceptions to this policy.3. We will be including a legal trailer or disclaimer message to the bottom of every outgoing Internet eMail. The legal disclaimer text is as follows:""This e-mail is the property of Enron Corp. and/or its relevant affiliate and may contain confidential and privileged material for the sole use of the intended recipient (s). Any review, use, distribution or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive for the recipient), please contact the sender or reply to Enron Corp. at enron.messaging.administration@enron.com and delete all copies of the message. This e-mail (and any attachments hereto) are not intended to be an offer (or an acceptance) and do not create or evidence a binding and enforceable contract between Enron Corp. (or any of its affiliates) and the intended recipient or any other party, and may not be relied on by anyone as the basis of a contract by estoppel or otherwise. Thank you. ""\t\tFor questions, please call the Resolution Center at ext. 31411."
4092,"Tue, 15 May 2001 04:04:00 -0700 (PDT)",joannie.williamson@enron.com,joannie.williamson@enron.com,,test,skilling-j,discussion_threads,2001-05-15 11:04:00+00:00,test,test
4260,"Mon, 6 Nov 2000 09:49:00 -0800 (PST)",seth.spalding@epoch.com,jeff.skilling@enron.com,Bandwidth optimization,"Jeff,\nSeth Spalding here, director of research at epoch partners. We met via\nsatellite this january when you presented at CE unterberg towbins conference\nin New York. I have since moved from ceut to epoch partners. In any case, I\nran across a company, backed by bill tai at redpoint ventures, that has some\nexcellent distributed IP technology used to bring SS7 like functionality to\nIP networks. I thought you or someone at enron might be interested in\nspeaking with them in light of your bandwidth exchange plans. The company is\ncalled eyefrog, and has nothing of depth available on their website. If this\nwould be of interest to you, please let me know and I would be happy to put\nyou in touch.\nRegards,\nSeth Spalding\n--------------------------------\nSeth Spalding\nDirector, Equity Research\nEpoch Partners\n415-315-3155\nsent via wireless",skilling-j,discussion_threads,2000-11-06 17:49:00+00:00,"Jeff,Seth Spalding here, director of research at epoch partners. We met viasatellite this january when you presented at CE unterberg towbins conferencein New York. I have since moved from ceut to epoch partners. In any case, Iran across a company, backed by bill tai at redpoint ventures, that has someexcellent distributed IP technology used to bring SS7 like functionality toIP networks. I thought you or someone at enron might be interested inspeaking with them in light of your bandwidth exchange plans. The company iscalled eyefrog, and has nothing of depth available on their website. If thiswould be of interest to you, please let me know and I would be happy to putyou in touch.Regards,Seth Spalding--------------------------------Seth SpaldingDirector, Equity ResearchEpoch Partners415-315-3155sent via wireless","Jeff,Seth Spalding here, director of research at epoch partners. We met viasatellite this january when you presented at CE unterberg towbins conferencein New York. I have since moved from ceut to epoch partners. In any case, Iran across a company, backed by bill tai at redpoint ventures, that has someexcellent distributed IP technology used to bring SS7 like functionality toIP networks. I thought you or someone at enron might be interested inspeaking with them in light of your bandwidth exchange plans. The company iscalled eyefrog, and has nothing of depth available on their website. If thiswould be of interest to you, please let me know and I would be happy to putyou in touch."

In [27]:
df_vo2 = df[['from', 'to', 'subject', 'date_clean', 'custodian', 'folder_source', 'body_clean']]
df_vo2 = df_vo2.rename(columns={'date_clean':'date'})

In [28]:
df_vo2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2476 entries, 156 to 5166
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   from           2476 non-null   object
 1   to             2476 non-null   object
 2   subject        2476 non-null   object
 3   date           2476 non-null   datetime64[ns, UTC]
 4   custodian      2476 non-null   object
 5   folder_source  2476 non-null   object
 6   body_clean     2476 non-null   object
dtypes: datetime64[ns, UTC](1), object(6)
memory usage: 154.8+ KB

### Summary

In [29]:
print(f"Unique Emails: {len(df)}")
print(f"Unknown Recipients: {(df['to'] == 'Unknown Recipient').sum()}")

Unique Emails: 2476
Unknown Recipients: 186

In [32]:
df_vo2.to_csv("clean_emails.csv", index=False)